name: iac-monorepo-template-infra-base
description: Base infrastructure for the monorepo
main: index.ts
runtime:
  name: nodejs
  options:
    packagemanager: npm
config:
  pulumi:tags:
    value:
      pulumi:template: aws-typescript
